# 2026-08-17 重要论文全文精读

Model: `deepseek-v4-pro`

Selected papers: 3

## Table of Contents

- [1. Think in Latent, Explain in Language: Self-Explainable Latent Reasoning](#paper-1)
- [2. ForgeWM: Progressive Causal Training for Few-Step Action-Conditioned Video World Models](#paper-2)
- [3. Marionette: Predicting World States, Rendering Geometry, Painting Appearance](#paper-3)

---

<div id='paper-1'></div>

## [1] 精读报告

# Think in Latent, Explain in Language: Self-Explainable Latent Reasoning

**Authors**: Dayuan Zhao, Shengcao Cao, Yu-Xiong Wang, Liang-Yan Gui
**Venue**: arXiv
**Link**: https://arxiv.org/abs/2608.13570
**PDF**: https://arxiv.org/pdf/2608.13570
**Importance**: 高优先级 (96.2)
**Why selected**: Directly advances the user's top-priority continuous latent reasoning direction with a novel self-explainable framework that removes external decoders. Signals: continuous latent reasoning, self-explainable CoT, unified multi-task training, LLM and VLM validation, token efficiency
**Source note**: PDF full text extracted; high-value sections were selected for the model context.

---

## 一句话总结 / One-liner

SELR 通过同时优化 Answer Loss 和 CoT Loss，让同一个模型在连续 latent 空间中进行高效推理，并能把自身 latent thoughts 解码为人类可读的 CoT，从而去掉外部 decoder。

SELR jointly trains a single model with an Answer Loss and a CoT Loss to reason efficiently in continuous latent space and decode its own latent thoughts into human-readable CoT, removing the need for external decoders.

---

## 动机 / Motivation

### 中文概述
- **要解决的问题**：连续 latent reasoning 能显著提升 token 效率，但会把思维过程压缩成不透明 embedding，难以解释。现有方案存在明显 trade-off：Coconut 等是“黑箱”，Heima 等则依赖独立的 post-hoc decoder，带来额外参数开销，并且解释过程与实际推理过程脱钩。
- **针对的 gap**：缺少一个统一框架，同时解决 latent reasoning 的监督问题（人类无法为 continuous thought 标注 ground truth）和可解释性问题。
- **关键观察 / 出发点**：文本 CoT Loss 可以作为丰富的监督信号，指导 latent thought 的形成；同时，如果让同一个模型把自己的 latent representation 解码回文本，就能让 latent 表征本身与人类逻辑对齐，兼顾效率、监督和可解释性。

### English Summary
The paper targets the tension between efficient but opaque continuous latent reasoning and post-hoc explainability via separate decoders. It observes that text CoT can provide supervision for latent thoughts, and that forcing the same model to decode its own latent representations can make them inherently interpretable.

---

## 核心方法 / Core Method

### 中文概述
- **整体框架**：SELR 分为两个阶段。
  1. **Latent Space Reasoning**：模型接收 image/question（VLM）或文本问题（LLM），顺序生成多个 continuous latent thoughts，再生成最终 answer。与 Coconut 类似，latent thoughts 是连续 embedding，不是一个一个 discrete text token。
  2. **CoT Decoding**：把刚生成的 latent thoughts 重新输入同一个模型，并附上 decoding prompt，让模型将 latent thoughts 解码为 Summary / Caption / Reasoning 等人类可读文本。
- **核心机制 / 训练目标**：多任务学习，同时优化两个 loss：
  - **Answer Loss**：保证 latent reasoning trajectory 能产生正确答案，维持任务性能。
  - **CoT Loss**：显式训练同一个模型把 latent representations 解码回 reasoning steps，使 latent thought 可解释，并反过来为 latent 表征提供文本监督。
- **与 closest work 的区别**：
  - 相比 **Coconut**：SELR 不牺牲可解释性，模型能自解码 latent thoughts。
  - 相比 **Heima**：Heima 需要为 Summary/Caption/Reasoning 分别训练多个独立 LLM decoder；SELR 只需一个模型，模型即 reasoner 也是 translator，避免外部 decoder 架构和解释与推理脱钩。
- **训练变体**：实验涉及 SELR (Single)、SELR (Multi, Uniform)、SELR (Multi, Exponential) 等变体。Single 是单阶段联合训练；Multi 则采用多阶段训练，并在某个 Single-Step Loss 中使用 uniform 或 exponential 分布来采样 latent thought step。

### English Summary
SELR uses a single model for two roles: generating continuous latent thoughts to reach an answer, and decoding those same latent thoughts into readable CoT. It is trained with an Answer Loss plus a CoT Loss. Unlike Heima, which requires multiple separate decoder models, SELR makes the original model its own translator.

---

## 启发性分析 / Insight Analysis

### 中文概述
- **CoT Loss 不只是可解释性，还提升质量**：Table 1 中 SELR (Answer Loss Only) 平均 accuracy 为 61.50，而加入 CoT Loss 的 SELR (Single/Multi) 平均 accuracy 提高到 63.72 / 63.47 / 63.31。说明 CoT Loss 对 latent thought 形成有实际监督作用，不仅是 decode 能力。
- **SFT 反而不如 base model**：Qwen2.5-VL-3B-Instruct-SFT 平均 accuracy 61.25，低于 base model 的 62.86。论文解释为 LLaVA-CoT-100k 强制三阶段 CoT 格式，带来 format shift，并迫使模型对简单问题也生成冗长推理。SELR 通过 latent 内部化，避免了这种文本格式负担。
- **token 效率与精度可同时获得**：SELR (Single) 平均 token 15.72，比 base model 的 49.92 减少约 68.5%，平均 accuracy 还略增 0.86%。Heima 虽然 token 也少（22.84），但平均 accuracy 相对于 base model 下降 1.92%。
- **多阶段训练优于单阶段**：SELR (Multi) 相比 SELR (Single) 进一步降低 token 数（13.32–13.47），且大多 benchmark 精度不降或略升，说明 staged decoding 训练有帮助。
- **局部能力退化**：MMVet 上 SELR 低于 base model，主要原因是 latent compression 天然限制长文本 / 多步生成能力，例如数学子问题和自由形式写作；Heima 在 MMVet 退化更严重（34.26 vs. SELR 的 36.10–41.88 区间）。这是 latent reasoning 的共有挑战。
- **Decoding quality**：在 LLaVA-CoT-100k 测试 split 上，SELR 的 decoded text 与 ground-truth Summary/Caption/Reasoning 的相似度（BLEU-4、METEOR、ROUGE-L、BERTScore、GPT-4o）一致优于 Heima baseline。
- **需要注意**：提取的文本中没有提供 error bars、多次运行方差或显著性检验，因此无法评估结果稳定性。

### English Summary
Ablations show that adding the CoT Loss improves answer quality over Answer Loss Only, and that multi-stage training further reduces token count. SFT on structured CoT data underperforms the base model, while SELR avoids this format shift. Token efficiency and accuracy can improve simultaneously. The main weakness is long-form/multi-step generation, especially on MMVet. No statistical significance information is reported in the extracted text.

---

## 实验设计 / Experimental Design

| 维度 | 内容 |
|------|------|
| 数据集 | **VLM 训练**：LLaVA-CoT-100k（100k image-text pairs，每个样本有 Summary/Caption/Reasoning 三阶段 CoT）。**LLM 训练**：GSM8k-Aug（385k GPT-4 生成的 math problems）。**VLM 评估**：MMStar、MMBench V1.1、MMVet、MathVista、AI2D、HallusionBench。**LLM 评估**：GSM8k test、SVAMP、MultiArith、GSM-Hard（OOD）。**Decoding quality**：LLaVA-CoT-100k 的 5% test split。 |
| Baseline | **VLM**：Qwen2.5-VL-3B-Instruct、Qwen2.5-VL-3B-Instruct-SFT（同数据文本 CoT SFT）、Heima reimplementation、SELR 各变体。**LLM**：Coconut、CoLaR（使用其最佳报告结果，test-time compression factor=2）、CoT-SFT、SELR (Single/Multi)。HRPO 与 CODI 被排除，理由分别是混合 latent/text 而非 fully latent、以及没有 decode/explain 机制；这种排除合理但可能降低可比性。 |
| 评估指标 | **VLM/LLM**：accuracy 与 generation token count；**decoding quality**：BLEU-4、METEOR、ROUGE-L、BERTScore、GPT-4o similarity。另外 Appendix G 报告 wall-clock inference latency，SELR 相比 SFT 达到 8.7× speedup。 |
| 消融实验 | ① Answer Loss Only vs. SELR：验证 CoT Loss 的价值；② SELR vs. SFT：证明性能提升来自 latent internalization，而非数据集本身；③ SELR (Single) vs. SELR (Multi)：验证多阶段训练；④ Uniform vs. Exponential 的 Single-Step Loss 采样分布；⑤ LLM 与 VLM 分别验证框架在不同 modality 的适用性。 |
| 统计显著性 | 提取文本中**未报告** error bars、多次运行均值方差或显著性检验；因此无法判断提升是否统计显著。 |

---

## 局限性与展望 / Limitations & Future Work

### 中文概述
- **作者明确指出的 limitation / future work**：需要一个稳定的、可学习的 stopping mechanism。论文指出这是 latent reasoning 的重要挑战；当前 latent thought 数量或停止条件可能依赖启发式。
- **论文中观察到但未作为核心 limitation 强调的问题**：
  - VLM 在 MMVet 上不如 base model，原因是 multi-step reasoning 与 long-form generation 被 latent compression 限制。
  - LLM 实验中 SELR 虽然超过 Coconut，但仍明显低于 CoT-SFT（GSM8k：42.46 vs. 64.06），说明在小规模 LLM 上，目前 latent reasoning 的绝对推理质量仍有差距。
- **可补充的未提及 limitation**：
  - 可解释性的“faithfulness”尚未被严格验证；CoT Loss 优化的是 decoded text 与 ground-truth 的相似度，不能直接证明 decoded CoT 忠实反映了 latent thought 的实际因果作用。
  - 自动化 decoding quality 指标（BLEU/METEOR/ROUGE/BERTScore/GPT-4o）只能衡量表面相似度，不能替代 human evaluation 或 causal intervention。
  - 实验规模主要停留在 1B/3B；7B 与无固定格式数据集的泛化结果只在附录中提及，主文证据有限。
- **Future directions**：学习 stopping mechanism；更大规模 LLM/VLM 验证；更严格的 faithfulness 评估；将 SELR 与 RLVR、process reward 或 latent 搜索结构结合；扩展到非结构化推理数据。

### English Summary
The authors acknowledge the need for a stable learned stopping mechanism. Observed but less emphasized limitations include MMVet long-form degradation and an LLM accuracy gap relative to CoT-SFT. Additional concerns include unverified faithfulness of self-decoded explanations, automatic decoding metrics only, and limited main-text evidence at larger scales.

---

## 个人思考 / Personal Takeaways

- **核心贡献简洁而有效**：一个共享 latent 表示同时被 Answer Loss 和 CoT Loss 约束，是一个很自然的“监督 + 可解释性”统一方案。相比外挂 decoder，self-decoding 减少参数和 pipeline 复杂度，工程上更干净。
- **最大的未解决问题是 faithfulness**：模型能够把 latent 解码成漂亮文本，不代表解码文本就是模型推理的真实原因。后续值得加入 intervention / ablation on latent dimensions，或设计 cycle consistency：latent → text → re-encode → latent’，要求两段 latent 对齐，以强化解释的因果一致性。
- **LM 与 VLM 的效果差异值得关注**：在 LLM 上 SELR 与 CoT-SFT 差距明显，而在 VLM 上 SELR 反而比文本 CoT SFT 更有效。这暗示 latent reasoning 的最大收益可能在于 text 是 bottleneck 的场景（如多模态），而不是纯文本数学题。
- **token efficiency 的收益显著**：SELR (Multi) 平均 13 tokens vs. SFT 218 tokens，推理速度快 8.7×，这对生产环境中的 reasoning 成本很有价值。
- **可进一步探索的点**：把 CoT Loss 扩展为 process reward / RLVR 信号；在 VLM 中利用 continuous visual embedding 与 latent thought 的同构性做更深融合；为 stopping 引入可学习的 end-of-thought token 与长度正则。


---

<div id='paper-2'></div>

## [2] 精读报告

# ForgeWM: Progressive Causal Training for Few-Step Action-Conditioned Video World Models

**Authors**: Xinye Li, Lingshuai Lin, Lei Wang, Liuzhou Zhang, Jialin Cui, Qingshan Li, Guanchu Wang, Qingbin Liu, Xi Chen, Jiang Bian, Wai Lam
**Venue**: arXiv
**Link**: https://arxiv.org/abs/2608.14022
**PDF**: https://arxiv.org/pdf/2608.14022
**Importance**: 高优先级 (95.0)
**Why selected**: Directly advances few-step causal video world models with progressive distillation, strongly matching the user's world model and video generation priorities. Signals: world model, video generation, few-step causal generation, distillation, Minecraft/FPS
**Source note**: PDF full text extracted; high-value sections were selected for the model context.

---

## 一句话总结 / One-liner

ForgeWM 提出四阶段渐进式因果训练框架，将双向 action-conditioned 视频生成器转化为 1/2/4 步少步交互式视频世界模型，并实现 game-native 控制对齐与 draft-preserving replay refinement。
English: ForgeWM introduces a four-stage progressive causal training framework that converts a bidirectional action-conditioned video generator into budget-specialized few-step world models with game-native control alignment and draft-preserving replay refinement.

## 动机 / Motivation

### 中文概述
- 论文要解决的问题：交互式视频世界模型需要低延迟的 causal generation，并对 game-native controls 作出可靠响应。
- 现有 causal distillation 已能实现 one/few-step 视频合成，但扩展到交互式世界模型仍很困难：discrete keyboard states 和 continuous mouse motion 必须在 temporally compressed latent chunks 中保持对齐，并且要贯穿 causal training 与 autoregressive rollout。
- 关键观察：因果生成同时改变输入分布和模型状态。推理时 denoiser 面对的是模型自己生成的有缺陷视觉历史，而不是干净数据；action histories 和 key–value caches 必须与生成的 latent chunks 同步。更少的 denoising steps 会放大这些状态中的错误，并在自回归中持续传播。
- 这在 game-native controls 下尤其严重：键盘/鼠标控制以视频帧率进入专用通路，不能被简单降级为 camera trajectory，因此训练框架必须在 adaptation 和 distillation 全过程中保留 control interface、action-to-latent alignment 和 causal state-update protocol。
- 目标 gap：如何把 teacher-forced causalization、few-step distillation、on-policy self-rollout 这类 causal video 方法，扩展到 frame-rate discrete/continuous game controls 的转换与对齐。

### English Summary
The paper targets the gap between general few-step causal video distillation and interactive world models. Low-step autoregressive generation is fragile because visual history, action streams, and KV caches must stay aligned with compressed latent chunks. ForgeWM studies how to preserve frame-aligned keyboard and mouse controls as clean context gives way to generated history.

## 核心方法 / Core Method

### 中文概述
- 总体框架：ForgeWM 从同一个 base generator 分出两条支路——bidirectional domain teacher 与 causal student，二者共享初始化，最终在 student 的 autoregressive self-rollout 上通过 on-policy distribution matching 交汇。
- 基础生成器采用 flow-matching objective：\(z_\sigma=(1-\sigma)z+\sigma\epsilon\)，训练 velocity predictor，并定义 clean prediction \( \hat{z}_\theta(z_\sigma,\sigma)=z_\sigma-\sigma v_\theta(z_\sigma,\sigma) \)。后续 consistency 和 distribution matching 阶段都围绕该 clean prediction 进行。
- Game-native action interface：ActionModule 将 discrete keyboard state 作为 cross-attention keys/values 注入，windowed continuous mouse motion 与 visual features 融合后进入 temporal attention，而不是把控制压缩成 camera pose / PRoPE 编码。VAE 将 4 个视频帧压缩为 1 个 latent frame，每个 3-latent chunk 对应 12 个视频帧；rollout 时维护 visual KV cache 和独立的 keyboard/mouse caches，确保每个新 chunk 获得完整对齐的 action window。
- 四阶段训练：
  - **Stage 0: bidirectional domain adaptation**。在目标游戏域上做 full-clip bidirectional attention 的 flow matching 适配；该 checkpoint 作为 Stage 3 的 frozen real denoiser。
  - **Stage 1: teacher-forced causal training**。从 base 初始化第二支路，将 full temporal attention 替换为 block-wise causal attention：chunk 内部 bidirectional，chunk 间只能看到更早 chunk；训练时 noisy chunk i 看到干净的前序 chunk，学习因果执行模式但不接触自身 rollout 错误。
  - **Stage 2: causal consistency initialization**。从 Stage 1 初始化 generator、EMA copy 与 frozen teacher，用 48 级噪声 grid 采样相邻 pair；frozen teacher 做一次带 classifier-free guidance 的 Euler step，student 与 EMA stop-gradient target 做 consistency matching。此阶段使用 clean causal history，使 teacher Euler step 只需一次 forward，而不需要 autoregressive unroll。
  - **Stage 3: on-policy distribution matching**。student 进行 autoregressive self-rollout，每个新 chunk 以自己生成的历史为条件；对生成结果加噪后，用 frozen real denoiser 与 trainable fake denoiser 的 disagreement 构造梯度方向，并做 generator surrogate matching；fake denoiser 同时用 flow-matching loss 更新，从而减少 teacher forcing 造成的 clean-history mismatch。
- Budget-specialized students：训练 \(K\in\{1,2,4\}\) 专用 checkpoint；1/2-step 学生对第一个生成 latent chunk 使用固定 4-step schedule，之后按匹配的 K-step schedule，因此“1-step/2-step”指 steady-state denoising budget，而非完整 rollout 的 total calls。
- Dual-path deployment：在线交互用低延迟 1/2/4-step student 生成并保存 draft；离线 replay-time refinement 用同一个低步 student 对 saved draft 重新加噪，并在更大 denoising schedule 下 refine，无需额外 refiner 或第二个 checkpoint。
- 与 closest related work 的区别：Causal Forcing、Causal Forcing++、Causal-rCM、Self-Forcing 主要围绕 general video causalization/distillation；ForgeWM 的关键区别是把这一整套 progression 实例化到 game-native training-to-deployment 框架中，强调 frame-aligned discrete+continuous controls、budget-specialized checkpoints，以及 same-checkpoint draft-preserving replay refinement。

### English Summary
ForgeWM uses a shared generator with two branches: a frozen bidirectional domain teacher and causal students. It progresses through bidirectional domain adaptation, teacher-forced causal training, causal consistency distillation, and on-policy distribution matching on autoregressive self-rollouts. Game-native keyboard/mouse controls remain frame-aligned via a modular ActionModule and per-modality KV caches, yielding 1/2/4-step causal checkpoints and a same-checkpoint replay-refinement protocol.

## 启发性分析 / Insight Analysis

### 中文概述
- 可提取的机制性 insight：论文反复强调的错误耦合——visual、action、cache 三类状态在压缩采样中被同时放大——是四阶段设计的基础。Stage 1 只改变 temporal execution，Stage 2 再改变 sampling objective，Stage 3 再改变 history distribution，体现了分阶段解耦错误来源的思路。
- Stage 2 的实用 insight：在 clean causal history 条件下做 causal consistency distillation，使 teacher Euler step 只用一次 forward pass 即可计算，避免 autoregressive unroll 的高昂成本。
- Stage 3 的 insight：teacher forcing 学到的 causal 模型仍存在 clean-history mismatch；通过 on-policy self-rollout 加噪并与 real/fake denoiser disagreement 匹配，让学生适应自生成历史分布。
- Replay-time refinement 的启发：用同一个 1-step checkpoint re-noise 并 refine 已保存 draft，可匹配 4-step reference quality，同时比从纯噪声重新生成更接近 experienced trajectory（约三倍更接近）。这说明保留 draft 对轨迹一致性的价值很大。
- 局限说明：当前 extracted text 没有给出详细 ablation tables、定性错误分析、scaling 或理论分析；stage-wise ablations 在 Appendix A 中提到但未包含。因此无法评估各 stage 的量化贡献，也难以判断是否存在反直觉发现。若需要更深层的 insight 分析，extracted text 证据不足。

### English Summary
The key extracted insights are that progressive stage design separates temporal execution, sampling objective, and history distribution to control error coupling; clean-context consistency initialization enables cheap teacher Euler steps; on-policy matching reduces teacher-forcing mismatch; and draft-preserving replay refinement preserves trajectory closeness while improving quality. Detailed quantitative ablations and error analysis are not present in the extracted text.

## 实验设计 / Experimental Design

| 维度 | 内容 |
|------|------|
| 数据集 | Main quantitative dataset: GF-Minecraft，共 40,000 clips，分辨率 640×352；另有 gamepad-controlled FPS 域用于迁移验证，但 controlled quantitative comparison 仍集中在 paired Minecraft trajectories。数据选择契合 game-native 键鼠/手柄控制主张。 |
| Baseline | 论文称与 interactive world-model baselines 比较，但 extracted text 未列出具体 baseline 名称及配置；related work 提及 DIAMOND、GameNGen、Genie、MineWorld、LingBot-World 2.0、minWM、DreamX-World 1.0 等，但无法确认哪些被直接比较，fairness 无法从现有文本判断。 |
| 评估指标 | 核心指标包括 Imaging Quality、reference-aligned motion-profile agreement、action-sign accuracy、mouse-control accuracy、reference LPIPS；replay 实验额外关注 draft retention / closeness to experienced trajectory。具体数值未出现在 extracted text 中。 |
| 消融实验 | 论文提到 Appendix A 包含 stage-wise ablations，并比较 Stage 1–3 checkpoints 在共享 4-step inference schedule 下的表现；但 extracted text 未包含具体消融设置或结果。 |
| 统计显著性 | Extracted text 中未报告 error bars、多次运行或显著性检验，因此无法评估统计稳健性。 |

## 局限性与展望 / Limitations & Future Work

### 中文概述
- 作者明确说明的边界：结论中提到 controlled quantitative comparison 仍集中在 Minecraft；FPS/gamepad 场景展示了方法迁移，但没有对应的 controlled quantitative evaluation。除此之外，extracted text 没有单独的 Limitations 或 Future Work sections。
- 可能但未被作者明确讨论的限制：文章声称 low-latency，但 extracted text 没有提供实际 latency、FLOPs、显存或 real-time deployment 数据；baseline 具体名称与公平性不透明；主实验仅一个数据域（Minecraft），对其他游戏/环境的泛化尚未 controlled 验证；没有报告统计显著性；action-controllability 指标虽多，但未展示具体数值，难以判断效果幅度。
- 未来方向（推断，而非作者明确列出）：将 controlled quantitative evaluation 扩展到 FPS 或更多 action space；引入 flexible test-time budget（类似 AnyFlow）而不是固定 budget-specialized checkpoints；结合强化学习或在线 agent 做 policy-in-the-loop 评测；分析 action-cache misalignment 的 failure modes；提供更 system-level 的延迟与吞吐基准。

### English Summary
The extracted text contains no dedicated limitations/future-work section. The authors acknowledge that controlled quantitative results remain on Minecraft, while FPS is shown only as transfer. Unmentioned gaps include missing latency benchmarks, undisclosed baseline details and metrics, single-domain main evaluation, and no statistical significance reporting. Future directions inferred could cover broader domains, flexible budgets, policy-in-the-loop evaluation, and deployment-level latency analysis.

## 个人思考 / Personal Takeaways

- 方法设计层面：把复杂问题（双向生成器 → 少步因果世界模型）拆成四个阶段，每阶段只改变 temporal execution / objective / history distribution 中的一个关键维度，思路清晰，便于 debug 和 ablation。这种「渐进式分布调整」对训练世界模型是很好的工程范式。
- 动作对齐层面：keyboard/mouse 以 frame-aligned 方式穿过 VAE 压缩和 causal cache，是游戏世界模型落地时非常实际但容易被忽略的问题。分开 visual KV、keyboard、mouse caches 并保持 aligned action window，是值得借鉴的实现细节。
- Replay refinement 层面：用同一个 checkpoint 做 draft 保存 + 离线 re-noise/refine，不引入第二个 refiner，兼顾在线延迟和离线质量，且保留 experienced trajectory 的一致性。这个 trick 对 interactive video agents 的部署有直接借鉴意义。
- 批判性评估：由于 extracted text 缺少具体实验表格和消融数值，「leading evaluated systems」「matches four-step reference quality」等核心结论目前只能作为方向性判断。后续阅读需要重点查看 Appendix A 和实验表格，确认 baseline 公平性、latency 数据、阶段贡献和统计稳定性。
- Follow-up research 思路：可以尝试将该四阶段 recipe 迁移到机器人 manipulation 或驾驶等高频控制 domain；探索 off-budget schedule 下 frozen 1-step checkpoints 的稳定性边界；把 action-cache alignment 的失败模式做成 diagnostic benchmark；或将 replay-time refinement 与 RL policy 的 offline replay buffer 结合，作 policy improvement。


---

<div id='paper-3'></div>

## [3] 精读报告

# Marionette: Predicting World States, Rendering Geometry, Painting Appearance

**Authors**: Zian Meng, Zhen Li, Chuanhao Li, Qiang Li, Kaipeng Zhang
**Venue**: arXiv
**Link**: https://arxiv.org/abs/2608.14530
**PDF**: https://arxiv.org/pdf/2608.14530
**Importance**: 高优先级 (94.86)
**Why selected**: 显式3D世界状态+零参数渲染+视频扩散外观合成，直接契合世界模型与连续多模态方向，且可控性与长时一致性突出。 Signals: 世界模型, 视频扩散, 显式3D状态, 可控生成, 长时一致性
**Source note**: PDF full text extracted; high-value sections were selected for the model context.

---

## 一句话总结 / One-liner

Marionette 将交互式游戏世界模型拆成显式 276 维 3D 状态、零参数几何渲染器与视频扩散外观模型，使几何和遮挡由构造保证精确，并把控制变成对单个 action token 的覆盖。

Marionette factors an interactive game world model into an explicit 276-D 3D state, a zero-parameter geometry renderer, and a video-diffusion appearance model, making geometry and occlusion exact by construction and control a single-token overwrite.

---

## 动机 / Motivation

### 中文概述
- 现有交互式游戏世界模型通常直接在 pixel 或 latent space 自回归生成视觉观测，pose、geometry、occlusion、object identity 和控制效果都必须由同一个生成序列隐式维护。
- 长时间 rollout 中，模型反复接收自己的输出，这些隐式性质上的误差会逐步累积，导致一致性和可控性脆弱。
- 本文的关键观察是：video 是低维 world state 的高维观测。直接学习 p(video) 会把 physics、identity、control 都纠缠在像素空间中。
- 将问题分解为 p(video) = ∫ p(obs | s) p(s_{t+1:} | s≤t, control) ds，可以让 dynamics 与 appearance 条件独立。
- 神经模型擅长 appearance 和感知合理性，但不擅长长时间精确记录和离散逻辑；因此把必须精确的部分——geometry、occlusion、metric motion——交给确定性 renderer，就像语言模型 agent 使用计算器一样。
- 例证来自 Minecraft redstone：redstone lamp 是否亮起取决于电路逻辑状态，而不是相邻像素；生成下一帧的模型可以生成一个看似合理但忽略该状态的帧。

### English Summary
Existing interactive game world models autoregress visual observations in pixel or latent space, forcing structured properties such as pose, geometry, and occlusion to be implicitly maintained by the generative sequence. Errors accumulate over long horizons. The paper proposes explicitly modeling the world state and delegating exact computations to a fixed renderer, while leaving appearance to neural models.

---

## 核心方法 / Core Method

### 中文概述
- 整体 pipeline 由三部分组成：ActionGPT（决策）→ PoseGPT（动画）→ zero-parameter graphics bridge（确定性渲染）→ observation model（视频扩散外观合成）。
- 显式世界状态 st ∈ R276：编码两个 articulated entities，即 monster 和 player character（hunter）。状态包含 root displacement、root-relative joint positions、weapon sub-state，以及 6D root rotations。
- 状态表示对全局位置和朝向具有不变性：joint 相对 root 存储，root motion 逐帧使用 delta。
- ActionGPT：一个 compact causal transformer（4 layers，width 256，约 2.5M 参数），逐帧逐实体自回归预测离散 action token，同时回归下一帧 root motion 和 orientation。
- 控制注入：由于 action 是显式 token，控制就是覆盖该 token；也可覆盖 root translation/rotation。无需重新训练，也无需辅助 conditioning network。
- PoseGPT：更大的 causal transformer（8 layers，width 512，约 25M 参数），将选中的 action tokens 和最近 body state 映射到下一帧 258D body pose。
- 两阶段 rollout 在有限 attention window 内循环；可选 terrain conditioning 以 egocentric height patch 和 per-joint ground clearances 输入两个 stage，并带有 ground-contact 与 non-penetration objectives。
- Zero-parameter graphics bridge：用 Gram–Schmidt orthonormalization 将 6D rotation 转成 rotation matrix；通过 cumulative sum 积分 root delta 得到世界系 root trajectory；重建 metric world-space skeletons，并 rasterize 成 pose-control video。
- 所有几何步骤都是 closed-form：world-space consistency、正确 occlusion ordering 和 metric scale 由构造保证。
- Bridge 构建三通道 geometry buffer：height、per-joint identity、inverse depth，供 observation model 读取。
- Observation model 是 control-conditioned video-diffusion，将 pose-control video 渲染成 photorealistic RGB，并通过 chunk-relay 实现长时间 horizon。
- 与相关工作的主要区别：前向 dynamics 放在显式 metric articulated state 中，graphics bridge 没有任何可学习参数；相比之下，pixel/latent world model 将一致性隐式存在网络中，而 pose-guided synthesis 通常把 pose 信号当作外部输入而非自行预测并 rollout。

### English Summary
Marionette has a two-stage dynamics model: ActionGPT predicts discrete per-entity action tokens, and PoseGPT turns them into a continuous articulated state. A zero-parameter graphics bridge converts the state into pose-control video with exact geometry and occlusion. A control-conditioned video-diffusion model then synthesizes RGB appearance, conditioned on the rendered control signals over chunk-relay for long horizons.

---

## 启发性分析 / Insight Analysis

### 中文概述
- 控制注入具有因果效果：强制替换错误 action stream 可改变 root-aligned joint error 达 31%（48 held-out segments），说明显式 action token 对后续 pose 有实际控制力。
- 长时间行为可以在 state 层被修复：自由 rollout 中两个生成角色漂移到 21.2 m（recorded sessions 约 5 m），且约三分之一帧出现地面穿透。
- 只对显式 state 施加两个规则——terrain collider 和 separation cap——地面穿透 reduce 66%，并保持两角色距离接近 recorded state，且不需要修改 observation model。
- 外观保真度没有可检测损失：predicted pose 的 FVD 为 831，recorded pose 为 799。
- 消融显示 terrain collider 将 ground penetration CFR 从 0.337 降至 0.114；加入 separation cap 后，end separation 从 21.2 m 降至 5.1 m。
- 一个关键的 negative result：如果 constraint 以 body 上的 differentiable penalty 表达，优化器会将它 trade away；但同样的 constraint 作为 input feature + post-hoc projection 施加时，可以保持有效。
- 这支持一个核心观点：constraining what recurs 比 regularizing 一个无约束 generator 更有效。
- 同时也看到 factorization 的边界：geometry 保持精确，但 appearance 仍会随时间漂移，因为 observation model 的 appearance memory 只通过 chunk-relay seed 传播并逐渐衰减。

### English Summary
Ablations show forced action tokens have causal authority over pose (31% joint error change), and rules imposed on the explicit state repair long-horizon failures (66% less ground penetration, separation reduced to 5.1 m) without changing the observation model. FVD is 831 vs 799 for generated vs recorded pose. A key negative result: differentiable penalties on the body were optimized away, while input-feature constraints plus post-hoc projection held.

---

## 实验设计 / Experimental Design

| 维度 | 内容 |
|------|------|
| 数据集 | WildWorld dataset：public gameplay corpus，包含 recordings、per-frame action labels 和 per-entity explicit state；本文使用其中两个 synchronized views，并新发布 scanned terrain height fields。该数据集适配显式状态和 bridge 的监督需求。 |
| Baseline | 提取文本未列出具体 baseline 名称；仅提及 commercial general-purpose video generators 作为 qualitative reference（Appendix G），并以 recorded pose 作为外观保真度参照。Fairness 不能从现有文本完全判断。 |
| 评估指标 | root-aligned joint error（米）、end separation（米）、ground penetration CFR、FVD。另报告 48 held-out segments 的控制 mismatch 效果。 |
| 消融实验 | terrain collider 和 separation cap 规则消融：penetration 0.337→0.114，end separation 21.2→5.1 m；predicted vs recorded pose 的 observation model 效果：FVD 831 vs 799；控制 mismatch：joint error 变化 31%。 |
| 统计显著性 | 提取文本未报告 error bars、多次运行或统计显著性检验；无法评估结果稳定性。 |

---

## 局限性与展望 / Limitations & Future Work

### 中文概述
作者明确承认的局限性：
- **Appearance conditioning**：随着 horizon 增加，appearance 会漂移，而底下的 geometry 仍然是 state 精确规定的。原因是 pose-control video 只固定 geometry、depth 和 articulation；appearance 完全依赖 observation model 自己的 memory，且该 memory 只通过 chunk-relay seed 传播，作为 unrestricted autoregressive quantity 会逐渐衰减。解决方案是保留 bridge 不动，为每个 entity 提供 persistent reference images，并在每个 chunk 重新供给。
- **Coverage of the recorded state**：训练记录中有些出现在 RGB 中的 entity（如 AI companions 和 small monsters）没有 recorded joints，使 observation model 在训练时看到一部分 target 无法由 condition 解释。模型因此学会自己补充这些 entity；在推理时会出现没有 state 支撑的内容。解决方式是直接从 engine 记录这些 entity 的 skeletons。
- **Ground-truth and generated pose mismatch**：observation model 在 GT state 渲染的 pose-control video 上训练，因为只有 GT pose 有 paired real RGB；推理时却由 generated state 驱动，存在分布偏移。作者用 §4.4 的 bridge ablation 来界定可观测影响，并提出两个修复方向：在中间表示上施加 feasibility rules（rig limits、contact、joint ranges）；在训练时扰动 GT state，使 observation model 学习它将被要求渲染的 pose 领域。

未提及但潜在的重要局限：
- 当前实验场景集中在单一交互式游戏中的两个 articulated entities，对其他游戏、更多实体数量、更复杂场景和更大动作词汇的泛化能力尚未验证。
- 文本未报告统计显著性信息，因此结果的可重复性和波动性无法判断。

未来方向主要包括：persistent appearance reference；补齐所有可见 entity 的显式状态；建立更完整的 feasibility rules；用扰动后的 GT pose 训练 observation model；将成熟 motion generation 模型（如 ARDY、Kimodo）直接接入 dynamics 阶段。

### English Summary
Author-acknowledged limitations include appearance drift over horizons due to weak persistent memory, missing recorded joints for some visible entities, and distribution shift between ground-truth training pose and generated inference pose. Proposed fixes include persistent reference images, recording all entity skeletons, enforcing feasibility rules on the intermediate representation, and perturbing ground-truth pose during training. Scope is currently limited to one game with two articulated entities.

---

## 个人思考 / Personal Takeaways

- 本文的核心设计原则很有复用价值：把“必须精确”的部分交给 deterministic tool，而不是希望一个无约束 generator 在长期自回归中自行保持几何、遮挡和 metric 一致性。
- 最具启发性的是 negative result：同一个 constraint，以 differentiable penalty 形式加在 body 上会被优化器 trade away，而以 input feature + post-hoc projection 形式施加在 bridge/state 上则能够保留。这意味着在设计世界模型时，约束执行的位置比约束本身更重要。
- 显式 state 让评估和修复都变得直接：可以用米来度量 drift、penetration 和 separation，并可以只修改 state 规则、不改 observation model 就修复行为。这种 decoupling 对后续可控生成研究是一个良好范例。
- FVD 831 vs 799 的结果支持：route appearance through predicted state 没有明显的 fidelity 代价，这是可推广的“结构化中间表示不牺牲外观质量”证据。
- 值得后续关注的问题：单游戏、双 entity 的设定较窄，能否扩展到更多 entity、更丰富动作接口和更一般 3D 场景仍需验证；appearance 的 persistent memory 与当前 state 解耦方式不对称，作者也承认这是未来重点。
- 如果要 follow-up，自然方向是：用一个成熟的 articulated motion 生成器替换 or 强化 PoseGPT；为 appearance 增加持久化 reference bank；扩展 feasibility rules；并在更多游戏和更高 entity 数下测试 method 的泛化能力。

